extends:
  - eslint:recommended
  - plugin:jest/recommended
  - prettier

plugins:
  - jest

env:
  node: true
  es6: true
  jest: true

parserOptions:
  ecmaVersion: 6

rules:
  eqeqeq: error
  no-console: off
  no-unused-vars: warn
  no-var: warn
  prefer-arrow-callback: warn
  prefer-const: [warn, {destructuring: all}]
